import React, { useState, useEffect } from "react";
import { api } from "../utils/api";
import { 
  Check, 
  CreditCard, 
  Sparkles, 
  ShieldCheck, 
  Activity, 
  Clock, 
  AlertCircle
} from "lucide-react";

export default function PricingPage() {
  const [subscription, setSubscription] = useState({
    plan: "Free Trial",
    status: "active",
    expires: "N/A"
  });
  const [loadingPlan, setLoadingPlan] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    // Read billing state
    const savedSub = localStorage.getItem("medscan_subscription");
    if (savedSub) {
      try {
        setSubscription(JSON.parse(savedSub));
      } catch (_) {}
    }
  }, []);

  const plans = [
    {
      name: "Free Trial",
      priceINR: 0,
      period: "forever",
      desc: "For individual clinicians researching pipeline capabilities.",
      features: [
        "Up to 5 document uploads / month",
        "Zero-Shot classification triage",
        "Basic clinical entity extraction (NER)",
        "Local vector search matching",
        "Standard General Reasoning Agent"
      ],
      color: "border-border",
      actionText: "Current Plan",
      actionDisabled: true,
    },
    {
      name: "Professional",
      priceINR: 2499,
      period: "month",
      desc: "For small-to-medium diagnostic labs and clinics.",
      features: [
        "Unlimited document uploads",
        "Advanced multi-agent graph reasoning",
        "TAPAS (table-based Q&A) sub-agent",
        "High-confidence clinical summaries",
        "Export parsed records to HL7 / FHIR",
        "Priority CPU queue scheduling",
        "24/7 technical support access"
      ],
      color: "border-primary ring-2 ring-primary/20 bg-primary/[0.02]",
      actionText: "Upgrade Now",
      actionDisabled: false,
      popular: true,
    },
    {
      name: "Enterprise",
      priceINR: 15999,
      period: "month",
      desc: "For hospital systems and developer APIs requiring custom models.",
      features: [
        "Dedicated local compute nodes",
        "Fine-tuned clinical summarization models",
        "Custom medical vocabulary database",
        "Webhook endpoints & event logs",
        "Zero-retention local data isolation",
        "HIPAA compliance certification",
        "Dedicated Integration Engineer"
      ],
      color: "border-secondary ring-2 ring-secondary/20 bg-secondary/[0.02]",
      actionText: "Contact Enterprise",
      actionDisabled: false,
    }
  ];

  const handleRazorpaySubscription = async (planName, amountINR) => {
    setError(null);
    if (amountINR === 0) return;

    if (planName === "Enterprise") {
      alert("Redirecting to enterprise sales. Please mail us at enterprise@medscan.ai");
      return;
    }

    setLoadingPlan(planName);

    // Verify if Razorpay SDK is loaded
    if (!window.Razorpay) {
      setError("Razorpay SDK failed to load. Please verify your internet connection.");
      setLoadingPlan(null);
      return;
    }

    try {
      // 1. Create order on the backend
      const orderData = await api.createPaymentOrder(amountINR, planName);

      // 2. Initialize Razorpay Checkout
      const options = {
        key: "rzp_test_SvHSWdWK4Eu2Ra", // Using the provided test key
        amount: orderData.amount, // amount in paisa from backend
        currency: orderData.currency,
        order_id: orderData.order_id, // Pass the order ID generated by backend
        name: "MedScan AI",
        description: `${planName} SaaS Plan Subscription`,
        image: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏥</text></svg>",
        handler: async function (response) {
          try {
            // 3. Verify payment signature on the backend
            await api.verifyPayment(
              response.razorpay_payment_id,
              response.razorpay_order_id,
              response.razorpay_signature
            );

            // Success
            const upgradedSub = {
              plan: planName,
              status: "active",
              expires: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString(),
              payment_id: response.razorpay_payment_id
            };
            localStorage.setItem("medscan_subscription", JSON.stringify(upgradedSub));
            setSubscription(upgradedSub);
            setLoadingPlan(null);
            
            alert(`Subscription Successful!\nPlan: ${planName}\nPayment ID: ${response.razorpay_payment_id}`);
            window.location.reload();
          } catch (verificationError) {
            setError(verificationError.message || "Payment verification failed.");
            setLoadingPlan(null);
          }
        },
        modal: {
          ondismiss: function() {
            setLoadingPlan(null);
          }
        },
        prefill: {
          name: "Dr. Demo User",
          email: "doctor@medscan.ai",
          contact: "9999999999"
        },
        theme: {
          color: planName === "Enterprise" ? "#4f46e5" : "#14b8a6"
        }
      };

      const rzp = new window.Razorpay(options);
      rzp.on('payment.failed', function (response){
          setError(response.error.description || "Payment failed.");
          setLoadingPlan(null);
      });
      rzp.open();
    } catch (err) {
      setError(err.message || "Failed to initialize Razorpay checkout");
      setLoadingPlan(null);
    }
  };

  const handleCancelSubscription = () => {
    if (!window.confirm("Are you sure you want to cancel your premium subscription? Your access will return to the Free Trial tier.")) {
      return;
    }
    const defaultSub = {
      plan: "Free Trial",
      status: "active",
      expires: "N/A"
    };
    localStorage.setItem("medscan_subscription", JSON.stringify(defaultSub));
    setSubscription(defaultSub);
    window.location.reload();
  };

  return (
    <div className="space-y-12 py-4 animate-fadeIn">
      {/* Header */}
      <div className="text-center space-y-4 max-w-2xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-xs font-semibold text-primary">
          <CreditCard size={14} />
          <span>Flexible Billing & Subscriptions</span>
        </div>
        <h2 className="text-3xl md:text-5xl font-extrabold tracking-tight">Select your SaaS plan</h2>
        <p className="text-muted-foreground text-sm md:text-base leading-relaxed">
          Scale your clinical analysis with local pipeline hosting, advanced agents, and secure database ingestion.
        </p>
      </div>

      {/* Active Subscription Banner */}
      <div className="glass-card rounded-2xl p-5 border border-border flex flex-col md:flex-row md:items-center justify-between gap-4 max-w-4xl mx-auto shadow-sm">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
            <Activity size={24} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-bold text-sm">Active Plan: {subscription.plan}</span>
              <span className="bg-emerald-500/10 text-emerald-500 border border-emerald-500/20 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider">
                {subscription.status}
              </span>
            </div>
            <p className="text-xs text-muted-foreground mt-0.5">
              {subscription.plan === "Free Trial" 
                ? "You are currently running on sandbox evaluation parameters."
                : `Next billing date: ${subscription.expires}. Paid via Razorpay.`}
            </p>
          </div>
        </div>
        {subscription.plan !== "Free Trial" && (
          <button
            onClick={handleCancelSubscription}
            className="text-xs font-bold text-rose-500 border border-rose-500/20 hover:bg-rose-500/5 px-4 py-2 rounded-xl transition-all self-start md:self-center"
          >
            Cancel Subscription
          </button>
        )}
      </div>

      {/* Error Alert */}
      {error && (
        <div className="flex items-center gap-3 bg-destructive/10 border border-destructive/20 text-destructive p-4 rounded-xl text-sm max-w-4xl mx-auto">
          <AlertCircle size={18} />
          <span className="font-semibold">{error}</span>
        </div>
      )}

      {/* Pricing Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto items-stretch">
        {plans.map((plan, idx) => (
          <div 
            key={idx} 
            className={`
              glass-card rounded-3xl p-6 border flex flex-col justify-between relative transition-all duration-300 hover:translate-y-[-4px]
              ${plan.color}
            `}
          >
            {plan.popular && (
              <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 bg-primary text-primary-foreground font-extrabold text-[10px] uppercase tracking-widest px-3 py-1 rounded-full shadow-md shadow-primary/20">
                Most Popular
              </span>
            )}

            <div className="space-y-6">
              <div className="space-y-2">
                <h3 className="font-extrabold text-lg text-foreground">{plan.name}</h3>
                <p className="text-[11px] text-muted-foreground leading-normal min-h-[36px]">
                  {plan.desc}
                </p>
              </div>

              {/* Price */}
              <div className="flex items-baseline gap-1">
                <span className="text-3xl font-extrabold">
                  {plan.priceINR === 0 ? "Free" : `₹${plan.priceINR.toLocaleString()}`}
                </span>
                {plan.priceINR > 0 && (
                  <span className="text-xs text-muted-foreground font-semibold">/{plan.period}</span>
                )}
              </div>

              {/* Features List */}
              <div className="space-y-3.5 border-t border-border pt-5">
                <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider block">Features Include</span>
                <ul className="space-y-3 text-xs leading-normal">
                  {plan.features.map((feature, fIdx) => (
                    <li key={fIdx} className="flex items-start gap-2.5">
                      <Check size={14} className="text-primary shrink-0 mt-0.5" />
                      <span className="text-muted-foreground font-medium">{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Subscribe Action */}
            <div className="pt-6 mt-6 border-t border-border/60">
              <button
                type="button"
                disabled={plan.actionDisabled || loadingPlan !== null || subscription.plan === plan.name}
                onClick={() => handleRazorpaySubscription(plan.name, plan.priceINR)}
                className={`
                  w-full font-bold text-xs py-3 rounded-xl transition-all cursor-pointer shadow-md
                  ${subscription.plan === plan.name
                    ? "bg-muted text-muted-foreground border border-border cursor-not-allowed shadow-none"
                    : plan.name === "Professional"
                      ? "bg-primary text-primary-foreground hover:opacity-95 shadow-primary/10 hover:shadow-primary/20"
                      : "border border-border bg-card hover:bg-muted text-foreground"
                  }
                `}
              >
                {loadingPlan === plan.name 
                  ? "Loading checkout..." 
                  : subscription.plan === plan.name 
                    ? "Active Subscribed" 
                    : plan.actionText}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Trust Badge */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-6 text-muted-foreground pt-4">
        <div className="flex items-center gap-2 text-xs font-semibold">
          <ShieldCheck size={16} className="text-primary" />
          <span>Secured Sandbox Transactions</span>
        </div>
        <div className="flex items-center gap-2 text-xs font-semibold">
          <Clock size={16} className="text-primary" />
          <span>Instantly Activated Tiers</span>
        </div>
      </div>
    </div>
  );
}
